2016-10-07 16:45:51.085 [error] <0.205.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.210.0> exit with reason normal in context child_terminated
2016-10-11 11:48:47.654 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 11:49:31.579 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 11:49:57.854 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 11:57:27.795 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 11:58:29.145 [error] <0.209.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.214.0> exit with reason normal in context child_terminated
2016-10-11 12:00:12.785 [error] <0.141.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.146.0> exit with reason normal in context child_terminated
2016-10-11 12:01:14.915 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 12:02:19.400 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 12:02:41.633 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.158.0> exit with reason normal in context child_terminated
2016-10-11 12:04:57.314 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-10-11 12:06:42.278 [error] <0.141.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.146.0> exit with reason normal in context child_terminated
2016-10-11 12:07:09.261 [error] <0.141.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.146.0> exit with reason normal in context child_terminated
2016-10-11 12:08:38.197 [error] <0.141.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.146.0> exit with reason normal in context child_terminated
2016-10-11 12:10:35.762 [error] <0.141.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.146.0> exit with reason normal in context child_terminated
2016-10-11 12:11:05.775 [error] <0.141.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.146.0> exit with reason normal in context child_terminated
2016-10-11 12:14:32.546 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 12:15:03.164 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-10-11 12:19:21.994 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 12:20:29.620 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 12:21:19.971 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-10-11 12:30:17.224 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 12:32:25.600 [error] <0.158.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.163.0> exit with reason normal in context child_terminated
2016-10-11 12:47:23.709 [error] <0.152.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.157.0> exit with reason normal in context child_terminated
2016-10-11 12:47:46.919 [error] <0.141.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.146.0> exit with reason normal in context child_terminated
2016-10-11 17:13:22.262 [error] <0.267.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.272.0> exit with reason normal in context child_terminated
2016-10-11 17:14:17.876 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-11 17:14:40.531 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-11 17:15:18.599 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-11 17:16:34.958 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-11 17:16:47.875 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-12 11:22:57.447 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 11:34:58.454 [error] <0.227.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.232.0> exit with reason normal in context child_terminated
2016-10-13 11:35:34.630 [error] <0.353.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{noproc,{gen_server,call,[requester_pool,{checkout,#Ref<0.0.1.67>,true},5000]}},[{erlang,send,[requester_pool,{'$gen_cast',{cancel_waiting,#Ref<0.0.1.67>}},[noconnect]],[]},{gen_server,do_send,2,[{file,"gen_server.erl"},{line,416}]},{gen_server,do_cast,2,[{file,"gen_server.erl"},{line,232}]},{poolboy,checkout,3,[{file,"src/poolboy.erl"},{line,58}]},{poolboy,transaction,3,[{file,"src/poolboy.erl"},{line,74}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,...},...]}
2016-10-13 11:35:34.630 [error] <0.353.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: no such process or port in call to gen_server:call(requester_pool, {checkout,#Ref<0.0.1.67>,true}, 5000) in gen_server:terminate/7 line 826
2016-10-13 11:35:34.630 [error] <0.330.0> Supervisor {<0.330.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.353.0> exit with reason no such process or port in call to gen_server:call(requester_pool, {checkout,#Ref<0.0.1.67>,true}, 5000) in context child_terminated
2016-10-13 11:38:49.022 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.169.0> exit with reason normal in context child_terminated
2016-10-13 11:38:55.933 [error] <0.290.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: bad argument in call to erlang:length(<<"127.0.0.1:5000">>) in 'Elixir.KaribuexCli.Client':get_connection_string/2 line 48
2016-10-13 11:38:55.934 [error] <0.290.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: bad argument in call to erlang:length(<<"127.0.0.1:5000">>) in 'Elixir.KaribuexCli.Client':get_connection_string/2 line 48
2016-10-13 11:38:55.934 [error] <0.267.0> Supervisor {<0.267.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.290.0> exit with reason bad argument in call to erlang:length(<<"127.0.0.1:5000">>) in 'Elixir.KaribuexCli.Client':get_connection_string/2 line 48 in context child_terminated
2016-10-13 11:42:08.065 [error] <0.170.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.175.0> exit with reason normal in context child_terminated
2016-10-13 11:42:14.654 [error] <0.294.0> gen_server <0.294.0> terminated with reason: no match of right hand value [{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22
2016-10-13 11:42:14.654 [error] <0.294.0> CRASH REPORT Process <0.294.0> with 0 neighbours exited with reason: no match of right hand value [{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22 in gen_server:terminate/7 line 826
2016-10-13 11:42:14.655 [error] <0.295.0> gen_server <0.295.0> terminated with reason: no match of right hand value [{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22
2016-10-13 11:42:14.655 [error] <0.295.0> CRASH REPORT Process <0.295.0> with 0 neighbours exited with reason: no match of right hand value [{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22 in gen_server:terminate/7 line 826
2016-10-13 11:42:14.660 [error] <0.296.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{{badmatch,[{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000]},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,22}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.294.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 11:42:14.661 [error] <0.296.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{{badmatch,[{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000]},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,22}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.294.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 11:42:14.661 [error] <0.275.0> Supervisor {<0.275.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.294.0> exit with reason no match of right hand value [{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22 in context child_terminated
2016-10-13 11:42:14.661 [error] <0.273.0> Supervisor {<0.273.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.296.0> exit with reason {{{badmatch,[{<<"127">>,<<"0">>,<<"0">>,<<"1">>},5000]},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,22}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.294.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 11:43:21.302 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.169.0> exit with reason normal in context child_terminated
2016-10-13 11:43:30.139 [error] <0.288.0> gen_server <0.288.0> terminated with reason: no match of right hand value [{127,0,0,1},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22
2016-10-13 11:43:30.140 [error] <0.288.0> CRASH REPORT Process <0.288.0> with 0 neighbours exited with reason: no match of right hand value [{127,0,0,1},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22 in gen_server:terminate/7 line 826
2016-10-13 11:43:30.140 [error] <0.289.0> gen_server <0.289.0> terminated with reason: no match of right hand value [{127,0,0,1},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22
2016-10-13 11:43:30.145 [error] <0.290.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{{badmatch,[{127,0,0,1},5000]},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,22}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 11:43:30.145 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: no match of right hand value [{127,0,0,1},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22 in gen_server:terminate/7 line 826
2016-10-13 11:43:30.145 [error] <0.290.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{{badmatch,[{127,0,0,1},5000]},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,22}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 11:43:30.145 [error] <0.269.0> Supervisor {<0.269.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.288.0> exit with reason no match of right hand value [{127,0,0,1},5000] in 'Elixir.KaribuexCli.Requester':handle_call/3 line 22 in context child_terminated
2016-10-13 11:43:30.146 [error] <0.267.0> Supervisor {<0.267.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.290.0> exit with reason {{{badmatch,[{127,0,0,1},5000]},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,22}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 11:44:02.981 [error] <0.164.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.169.0> exit with reason normal in context child_terminated
2016-10-13 11:44:09.281 [error] <0.290.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {timeout,{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 11:44:09.282 [error] <0.290.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 11:44:09.282 [error] <0.267.0> Supervisor {<0.267.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.290.0> exit with reason {timeout,{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 11:44:33.478 [error] <0.297.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {timeout,{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 11:44:33.478 [error] <0.297.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 11:44:33.478 [error] <0.267.0> Supervisor {<0.267.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.297.0> exit with reason {timeout,{'Elixir.GenServer',call,[<0.288.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 11:52:43.366 [error] <0.216.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.221.0> exit with reason normal in context child_terminated
2016-10-13 11:58:17.858 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.158.0> exit with reason normal in context child_terminated
2016-10-13 11:59:08.418 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 11:59:44.241 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 12:02:14.933 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 12:03:39.286 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 12:06:17.795 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 12:06:41.421 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 12:09:06.507 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.158.0> exit with reason normal in context child_terminated
2016-10-13 12:09:45.797 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 12:10:34.007 [error] <0.153.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.158.0> exit with reason normal in context child_terminated
2016-10-13 12:16:22.259 [error] <0.171.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.176.0> exit with reason normal in context child_terminated
2016-10-13 12:21:42.447 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 12:22:18.317 [error] <0.285.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {timeout,{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,12]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 12:22:18.317 [error] <0.285.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,12]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 12:22:18.317 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.285.0> exit with reason {timeout,{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,12]},5000]}} in context child_terminated
2016-10-13 12:29:53.724 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 12:32:03.904 [error] <0.142.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.147.0> exit with reason normal in context child_terminated
2016-10-13 12:37:32.254 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 12:39:05.259 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 12:39:18.434 [error] <0.283.0> gen_server <0.283.0> terminated with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 25
2016-10-13 12:39:18.434 [error] <0.283.0> CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 25 in gen_server:terminate/7 line 826
2016-10-13 12:39:18.435 [error] <0.284.0> gen_server <0.284.0> terminated with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 25
2016-10-13 12:39:18.441 [error] <0.285.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{{badmatch,{error,fsm}},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 12:39:18.441 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 25 in gen_server:terminate/7 line 826
2016-10-13 12:39:18.441 [error] <0.285.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{{badmatch,{error,fsm}},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 12:39:18.441 [error] <0.264.0> Supervisor {<0.264.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.283.0> exit with reason no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 25 in context child_terminated
2016-10-13 12:39:18.441 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.285.0> exit with reason {{{badmatch,{error,fsm}},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 12:40:02.078 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-10-13 12:40:03.225 [error] <0.289.0> gen_server <0.289.0> terminated with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 26
2016-10-13 12:40:03.225 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 26 in gen_server:terminate/7 line 826
2016-10-13 12:40:03.226 [error] <0.290.0> gen_server <0.290.0> terminated with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 26
2016-10-13 12:40:03.226 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 26 in gen_server:terminate/7 line 826
2016-10-13 12:40:03.231 [error] <0.291.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{{badmatch,{error,fsm}},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.289.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 12:40:03.231 [error] <0.291.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{{badmatch,{error,fsm}},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.289.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 12:40:03.231 [error] <0.270.0> Supervisor {<0.270.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.289.0> exit with reason no match of right hand value {error,fsm} in 'Elixir.KaribuexCli.Requester':handle_call/3 line 26 in context child_terminated
2016-10-13 12:40:03.232 [error] <0.268.0> Supervisor {<0.268.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.291.0> exit with reason {{{badmatch,{error,fsm}},[{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,26}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.289.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 12:48:55.938 [error] <0.300.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {timeout,{'Elixir.GenServer',call,[<0.298.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 12:48:55.938 [error] <0.300.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,[<0.298.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 12:48:55.939 [error] <0.268.0> Supervisor {<0.268.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.300.0> exit with reason {timeout,{'Elixir.GenServer',call,[<0.298.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 12:57:33.767 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 12:57:45.793 [error] <0.285.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {timeout,{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 12:57:45.793 [error] <0.285.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {timeout,{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 12:57:45.794 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.285.0> exit with reason {timeout,{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 12:59:22.128 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 12:59:46.853 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.153.0> exit with reason normal in context child_terminated
2016-10-13 12:59:56.569 [error] <0.272.0> gen_server <0.272.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 12:59:56.569 [error] <0.272.0> CRASH REPORT Process <0.272.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 12:59:56.570 [error] <0.273.0> gen_server <0.273.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 12:59:56.570 [error] <0.273.0> CRASH REPORT Process <0.273.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 12:59:56.575 [error] <0.274.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in 'Elixir.GenServer':call/3 line 604
2016-10-13 12:59:56.575 [error] <0.274.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in gen_server:terminate/7 line 826
2016-10-13 12:59:56.575 [error] <0.253.0> Supervisor {<0.253.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.272.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 12:59:56.575 [error] <0.251.0> Supervisor {<0.251.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.274.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 13:00:11.929 [error] <0.281.0> gen_server <0.281.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:11.929 [error] <0.281.0> CRASH REPORT Process <0.281.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:11.929 [error] <0.253.0> Supervisor {<0.253.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.281.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 13:00:11.931 [error] <0.283.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in 'Elixir.GenServer':call/3 line 604
2016-10-13 13:00:11.932 [error] <0.283.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in gen_server:terminate/7 line 826
2016-10-13 13:00:11.933 [error] <0.282.0> gen_server <0.282.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:11.933 [error] <0.282.0> CRASH REPORT Process <0.282.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:11.933 [error] <0.251.0> Supervisor {<0.251.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.283.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 13:00:16.747 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.153.0> exit with reason normal in context child_terminated
2016-10-13 13:00:18.785 [error] <0.272.0> gen_server <0.272.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:18.786 [error] <0.272.0> CRASH REPORT Process <0.272.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:18.786 [error] <0.273.0> gen_server <0.273.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:18.787 [error] <0.273.0> CRASH REPORT Process <0.273.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:00:18.787 [error] <0.253.0> Supervisor {<0.253.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.272.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 13:00:18.792 [error] <0.274.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in 'Elixir.GenServer':call/3 line 604
2016-10-13 13:00:18.792 [error] <0.274.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in gen_server:terminate/7 line 826
2016-10-13 13:00:18.792 [error] <0.251.0> Supervisor {<0.251.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.274.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 13:02:12.779 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 13:02:37.373 [error] <0.283.0> gen_server <0.283.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:02:37.373 [error] <0.283.0> CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:02:37.374 [error] <0.284.0> gen_server <0.284.0> terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:02:37.374 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24
2016-10-13 13:02:37.374 [error] <0.264.0> Supervisor {<0.264.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.283.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 13:02:37.378 [error] <0.285.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in 'Elixir.GenServer':call/3 line 604
2016-10-13 13:02:37.378 [error] <0.285.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in gen_server:terminate/7 line 826
2016-10-13 13:02:37.379 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.285.0> exit with reason bad argument in 'Elixir.KaribuexCli.Requester':handle_call/3 line 24 in context child_terminated
2016-10-13 13:03:30.117 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 13:07:20.897 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 13:07:32.236 [error] <0.283.0> gen_server <0.283.0> terminated with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,...>>) line 85
2016-10-13 13:07:32.236 [error] <0.283.0> CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,...>>) line 85 in gen_server:terminate/7 line 826
2016-10-13 13:07:32.237 [error] <0.284.0> gen_server <0.284.0> terminated with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,...>>) line 85
2016-10-13 13:07:32.237 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,...>>) line 85 in gen_server:terminate/7 line 826
2016-10-13 13:07:32.238 [error] <0.264.0> Supervisor {<0.264.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.283.0> exit with reason no function clause matching ezmq:send(<0.284.0>, <<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,...>>) line 85 in context child_terminated
2016-10-13 13:07:32.242 [error] <0.285.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{function_clause,[{ezmq,send,[<0.284.0>,<<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,77,111,100,117,108,101,84,101,115,116,164,101,99,104,111,145,10>>],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"pro..."},...]}]},...} in 'Elixir.GenServer':call/3 line 604
2016-10-13 13:07:32.242 [error] <0.285.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{function_clause,[{ezmq,send,[<0.284.0>,<<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,77,111,100,117,108,101,84,101,115,116,164,101,99,104,111,145,10>>],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"pro..."},...]}]},...} in gen_server:terminate/7 line 826
2016-10-13 13:07:32.243 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.285.0> exit with reason {{function_clause,[{ezmq,send,[<0.284.0>,<<149,0,180,48,98,100,55,101,97,56,49,102,53,49,97,50,98,52,50,48,100,100,97,174,85,115,101,114,77,111,100,117,108,101,84,101,115,116,164,101,99,104,111,145,10>>],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"pro..."},...]}]},...} in context child_terminated
2016-10-13 14:13:07.410 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 14:13:19.066 [error] <0.283.0> gen_server <0.283.0> terminated with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,...>>) line 85
2016-10-13 14:13:19.067 [error] <0.283.0> CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,...>>) line 85 in gen_server:terminate/7 line 826
2016-10-13 14:13:19.068 [error] <0.284.0> gen_server <0.284.0> terminated with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,...>>) line 85
2016-10-13 14:13:19.068 [error] <0.284.0> CRASH REPORT Process <0.284.0> with 0 neighbours exited with reason: no function clause matching ezmq:send(<0.284.0>, <<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,...>>) line 85 in gen_server:terminate/7 line 826
2016-10-13 14:13:19.074 [error] <0.285.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{function_clause,[{ezmq,send,[<0.284.0>,<<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,77,111,100,117,108,101,84,101,115,116,164,101,99,104,111,145,10,0>>],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"p..."},...]}]},...} in 'Elixir.GenServer':call/3 line 604
2016-10-13 14:13:19.075 [error] <0.285.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{function_clause,[{ezmq,send,[<0.284.0>,<<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,77,111,100,117,108,101,84,101,115,116,164,101,99,104,111,145,10,0>>],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"p..."},...]}]},...} in gen_server:terminate/7 line 826
2016-10-13 14:13:19.075 [error] <0.264.0> Supervisor {<0.264.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.283.0> exit with reason no function clause matching ezmq:send(<0.284.0>, <<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,...>>) line 85 in context child_terminated
2016-10-13 14:13:19.075 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.285.0> exit with reason {{function_clause,[{ezmq,send,[<0.284.0>,<<149,0,180,52,53,98,51,98,55,97,55,50,99,101,97,102,54,48,52,102,101,102,98,174,85,115,101,114,77,111,100,117,108,101,84,101,115,116,164,101,99,104,111,145,10,0>>],[{file,"src/ezmq.erl"},{line,85}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,25}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"p..."},...]}]},...} in context child_terminated
2016-10-13 14:13:58.892 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 14:15:12.830 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 14:17:43.365 [error] <0.283.0> gen_server <0.283.0> terminated with reason: no such process or port in call to gen_server:call(<0.284.0>, {connect,tcp,{127,0,0,1},5000,[]}) in gen_server:call/2 line 204
2016-10-13 14:17:43.366 [error] <0.283.0> CRASH REPORT Process <0.283.0> with 0 neighbours exited with reason: no such process or port in call to gen_server:call(<0.284.0>, {connect,tcp,{127,0,0,1},5000,[]}) in gen_server:terminate/7 line 826
2016-10-13 14:17:43.366 [error] <0.264.0> Supervisor {<0.264.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.283.0> exit with reason no such process or port in call to gen_server:call(<0.284.0>, {connect,tcp,{127,0,0,1},5000,[]}) in context child_terminated
2016-10-13 14:17:43.366 [error] <0.285.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{noproc,{gen_server,call,[<0.284.0>,{connect,tcp,{127,0,0,1},5000,[]}]}},{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 14:17:43.367 [error] <0.285.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{noproc,{gen_server,call,[<0.284.0>,{connect,tcp,{127,0,0,1},5000,[]}]}},{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 14:17:43.367 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.285.0> exit with reason {{noproc,{gen_server,call,[<0.284.0>,{connect,tcp,{127,0,0,1},5000,[]}]}},{'Elixir.GenServer',call,[<0.283.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 14:19:00.019 [error] <0.165.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.170.0> exit with reason normal in context child_terminated
2016-10-13 14:19:04.541 [error] <0.289.0> gen_server <0.289.0> terminated with reason: call to undefined function ezmq:disconnect/1 from 'Elixir.KaribuexCli.Requester':handle_call/3 line 30
2016-10-13 14:19:04.541 [error] <0.289.0> CRASH REPORT Process <0.289.0> with 0 neighbours exited with reason: call to undefined function ezmq:disconnect(<0.290.0>) in gen_server:terminate/7 line 826
2016-10-13 14:19:04.548 [error] <0.291.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{undef,[{ezmq,disconnect,[<0.290.0>],[]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,30}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.289.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 14:19:04.552 [error] <0.290.0> gen_server <0.290.0> terminated with reason: call to undefined function ezmq:disconnect/1 from 'Elixir.KaribuexCli.Requester':handle_call/3 line 30
2016-10-13 14:19:04.552 [error] <0.291.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{undef,[{ezmq,disconnect,[<0.290.0>],[]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,30}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.289.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 14:19:04.552 [error] <0.290.0> CRASH REPORT Process <0.290.0> with 0 neighbours exited with reason: call to undefined function ezmq:disconnect(<0.290.0>) in gen_server:terminate/7 line 826
2016-10-13 14:19:04.553 [error] <0.268.0> Supervisor {<0.268.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.291.0> exit with reason {{undef,[{ezmq,disconnect,[<0.290.0>],[]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,30}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.289.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 14:19:04.553 [error] <0.270.0> Supervisor {<0.270.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.289.0> exit with reason call to undefined function ezmq:disconnect(<0.290.0>) in context child_terminated
2016-10-13 14:22:21.857 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 14:22:28.567 [error] <0.274.0> gen_server <0.274.0> terminated with reason: call to undefined function ezmq:disconnect/1 from 'Elixir.KaribuexCli.Requester':handle_call/3 line 27
2016-10-13 14:22:28.567 [error] <0.274.0> CRASH REPORT Process <0.274.0> with 0 neighbours exited with reason: call to undefined function ezmq:disconnect(<0.279.0>) in gen_server:terminate/7 line 826
2016-10-13 14:22:28.568 [error] <0.264.0> Supervisor {<0.264.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.274.0> exit with reason call to undefined function ezmq:disconnect(<0.279.0>) in context child_terminated
2016-10-13 14:22:28.575 [error] <0.275.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{undef,[{ezmq,disconnect,[<0.279.0>],[]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,27}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.274.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 14:22:28.575 [error] <0.275.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{undef,[{ezmq,disconnect,[<0.279.0>],[]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,27}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.274.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in gen_server:terminate/7 line 826
2016-10-13 14:22:28.576 [error] <0.262.0> Supervisor {<0.262.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.275.0> exit with reason {{undef,[{ezmq,disconnect,[<0.279.0>],[]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,27}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.274.0>,{execute,<<"127.0.0.1:5000">>,[<<"UserModuleTest">>,<<"echo">>,10]},5000]}} in context child_terminated
2016-10-13 14:22:28.581 [error] <0.279.0> gen_server <0.279.0> terminated with reason: call to undefined function ezmq:disconnect/1 from 'Elixir.KaribuexCli.Requester':handle_call/3 line 27
2016-10-13 14:22:28.581 [error] <0.279.0> CRASH REPORT Process <0.279.0> with 0 neighbours exited with reason: call to undefined function ezmq:disconnect(<0.279.0>) in gen_server:terminate/7 line 826
2016-10-13 14:22:43.897 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 14:25:59.093 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.153.0> exit with reason normal in context child_terminated
2016-10-13 14:27:17.934 [error] <0.8794.0> Unable to load crypto library. Failed with error:
"load, Library load-call unsuccessful."
OpenSSL might not be installed on this system.

2016-10-13 14:27:17.958 [error] <0.263.0> gen_server <0.263.0> terminated with reason: {'module could not be loaded',[{crypto,strong_rand_bytes,"\n",[]},{'Elixir.SecureRandom',hex,1,[{file,"lib/secure_random.ex"},{line,56}]},{'Elixir.KaribuexCli.Request',new,3,[{file,"lib/request.ex"},{line,7}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,16}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}
2016-10-13 14:27:17.958 [error] <0.263.0> CRASH REPORT Process <0.263.0> with 0 neighbours exited with reason: call to undefined function crypto:strong_rand_bytes(10) in gen_server:terminate/7 line 826
2016-10-13 14:27:17.966 [error] <0.264.0> gen_server 'Elixir.KaribuexCli.Client' terminated with reason: {{undef,[{crypto,strong_rand_bytes,"\n",[]},{'Elixir.SecureRandom',hex,1,[{file,"lib/secure_random.ex"},{line,56}]},{'Elixir.KaribuexCli.Request',new,3,[{file,"lib/request.ex"},{line,7}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,16}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.263.0>,...]}} in 'Elixir.GenServer':call/3 line 604
2016-10-13 14:27:17.966 [error] <0.253.0> Supervisor {<0.253.0>,poolboy_sup} had child undefined started with {'Elixir.KaribuexCli.Requester',start_link,undefined} at <0.263.0> exit with reason call to undefined function crypto:strong_rand_bytes(10) in context child_terminated
2016-10-13 14:27:17.966 [error] <0.264.0> CRASH REPORT Process 'Elixir.KaribuexCli.Client' with 0 neighbours exited with reason: {{undef,[{crypto,strong_rand_bytes,"\n",[]},{'Elixir.SecureRandom',hex,1,[{file,"lib/secure_random.ex"},{line,56}]},{'Elixir.KaribuexCli.Request',new,3,[{file,"lib/request.ex"},{line,7}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,16}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.263.0>,...]}} in gen_server:terminate/7 line 826
2016-10-13 14:27:17.966 [error] <0.251.0> Supervisor {<0.251.0>,'Elixir.KaribuexCli.Supervisor'} had child undefined started with 'Elixir.KaribuexCli.Client':start_link(#{mercure_service => <<>>,my_test => <<"127.0.0.1:5000">>,sap_bridge => <<"192.168.0.1:9000">>}) at <0.264.0> exit with reason {{undef,[{crypto,strong_rand_bytes,"\n",[]},{'Elixir.SecureRandom',hex,1,[{file,"lib/secure_random.ex"},{line,56}]},{'Elixir.KaribuexCli.Request',new,3,[{file,"lib/request.ex"},{line,7}]},{'Elixir.KaribuexCli.Requester',handle_call,3,[{file,"lib/requester.ex"},{line,16}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,629}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,661}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]},{'Elixir.GenServer',call,[<0.263.0>,...]}} in context child_terminated
2016-10-13 14:27:33.546 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.153.0> exit with reason normal in context child_terminated
2016-10-13 14:36:22.454 [error] <0.148.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.153.0> exit with reason normal in context child_terminated
2016-10-13 15:09:19.018 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 15:11:06.833 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 15:11:37.270 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 15:12:49.054 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
2016-10-13 15:13:17.147 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child undefined started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}, link) at <0.164.0> exit with reason normal in context child_terminated
